#
#  Author: Hari Sekhon
#  Date: 2020-09-21 13:19:44 +0100 (Mon, 21 Sep 2020)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/kubernetes-templates
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#bases:
#  - ../../base

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  #- cronjob.yaml
  #- statefulset.yaml

# I prefer this to the JSON inline patch as it's separately usable from the CLI as well
patchesStrategicMerge:
  - deployment.patch.yaml
  # set in cronjob.yml now - besides this is too generic to apply here, doesn't contain name/namespace metadata necessary for patching selection
  #- cronjob-fix-stale.patch.yaml

images:
  - name: eu.gcr.io/myproject/someimage
    newName: eu.gcr.io/myproject/someotherimage
    newTag: "latest"

configMapGenerator:
  - name: my-env
    namespace: NAMESPACE
    literals:
    - env=dev
    - version=latest
